import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      reportsDirectory: "./coverage",
      // Restricted to sources: a bare `src/**` also pulls in index.css, which
      // reports as an uncovered file and drags the ratio down for nothing.
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/__tests__/**",
        // Generated by ts-rs and holding nothing but type declarations, so it
        // erases to zero executable lines and would only dilute the ratio.
        "src/bindings/**",
        // The React bootstrap; it runs only in a real browser window.
        "src/main.tsx",
      ],
    },
  },
});
