// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a successful merge.
 */
export type MergeReportDto = { page_count: number, bytes_written: number, };
