// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of one source at one position in the plan.
 */
export type PageSlotDto = { id: number, source: number, page: number, };
