// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageSlotDto } from "./PageSlotDto";
import type { SourceFileDto } from "./SourceFileDto";

/**
 * The whole document as the frontend sees it. Commands return a full snapshot
 * rather than a diff, so the UI never has to replay operations itself.
 */
export type PlanSnapshot = { slots: Array<PageSlotDto>, sources: Array<SourceFileDto>, };
