// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceStatusDto } from "./SourceStatusDto";

/**
 * A source file and the metadata the UI needs to label it. `kind` is `"pdf"`
 * or `"image"`; `grouping` is `"grouped"` or `"ungrouped"`; `file_name` is the
 * final path component, for display when the full path is too long.
 */
export type SourceFileDto = { id: number, path: string, file_name: string, kind: string, grouping: string, page_count: number, status: SourceStatusDto, };
