// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a source does or does not contribute pages. Tagged so TypeScript can
 * narrow on `kind` and still reach `reason`.
 */
export type SourceStatusDto = { "kind": "ready" } | { "kind": "encrypted" } | { "kind": "unreadable", reason: string, };
